name: db
channels:
    - defaults
dependencies:
    - python=3.10
    - pip=23.3.1
    - pip:
          - torch==2.2.1
          - torchvision==0.17.1
          - omegaconf==2.3.0
          - transformers==4.38.2
          - pytorch-lightning==2.2.1
          - einops==0.7.0
          - taming-transformers==0.0.1
          # visualizations
          - matplotlib==3.8.3
          - ipykernel
          - ipywidgets
